name: Kraika
favicon: null
layout_spectrum: 0.93823
typography_spectrum: 0.16897933627478778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#733466'
    - '#29bec4'
    - '#e81771'
    - '#5a6185'
    - '#009999'
  brandStrength: 0.8927738163620234
  lightness: 0.47307184850797057
  saturation: 0.6248274229001254
  rhythmicContrast: 0.41101485677063465
purpose: []
